### ISSUE TITLE
Task4

### ISSUE THREAD

**Issue by dao-olau** [csci3250-2019/project-team-a#13]
Please start to remember what you have done for C class. Or learn it anew.

Your tasks:

- [x] In code.c, write a piece of very simple (yet correct) C code (e.g. Hello World, simple for loop, simple if...then...else, etc.)
- [x] In readme.md, include your code (either copy & paste or include_relative)
- [x] Read this article to see how to get the GitHub shield for Travis CI, and put it inside readme.md with your code: https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7

(Note: Travis CI is already installed on this repo)

**Comment by wanruu** [comment]
Everything is done well.
