### ISSUE TITLE
Task5

### ISSUE THREAD

**Issue by wanruu** [csci3250-2019/project-team-a#16]
Now that your team has finished most of the tasks, you have to promote it! Your tasks:

- [x] Look at your team's page here: `https://csci3250-2019.github.io/(repo name)`
- [x] Go to the public repo of **`csci3250-2019.github.io`** in the CSCI3250 organization
- [x] Edit the file to add a link of your team, and request for review from @chuckjee

And there you're done!

**Comment by wanruu** [comment]
Hi, yytlee. Would you mind helping me double check the issue?

**Comment by kfcheung1016** [comment]
is this task completed?

**Comment by wanruu** [comment]
Yes. But according to instructions, it still needs to be double checked by someone.

**Comment by kfcheung1016** [comment]
then maybe i can just close this issue?

**Comment by wanruu** [comment]
Yes, of course. Thanks!

**Comment by kfcheung1016** [comment]
THANKS!
