### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by fe7ng654123** [csci3250-2019/project-team-a#3]
set up the file readme.md with the following contents:

- [x] 3 headings: Introduction, Code, and Contributors

- [x] Under Introduction, write a short summary of things your team will do according to the tasks inside the issues folder

- [x] Ensure your readme.md article is well-formatted with Markdown

**Comment by fe7ng654123** [comment]
I have not yet done the short summary of things our team will do. I will write it later

**Comment by atom1232** [comment]
Task1 is reviewed and close now
