### ISSUE TITLE
Task3

### ISSUE THREAD

**Issue by chang2000** [csci3250-2019/project-team-a#30]
Please explore the **Projects** tab

Your tasks:
- [x] Create a new project board (with any name), and use the **Basic Kanban** template, containing *"To do"*, *"In Progress"*, and *"Done"*
- [x] Set up these automations:
- When pull requests are added, put the item in "In progress"
- When issues are closed, put the item in "Done"
- When pull requests are merged, put the item in "Done"
- [x] Regularly visit the **Issues** and **Pull requests** tabs to make sure all items are marked with your project board

**Comment by chang2000** [comment]
Board Created

**Comment by wanruu** [comment]
Not all Pull requests are marked. But other tasks are all done perfectly.
