### ISSUE TITLE
Task3.md

### ISSUE THREAD

**Issue by wanruu** [csci3250-2019/project-team-a#9]
# #3: Project board

Please explore the **Projects** tab

Your tasks:
1. Create a new project board (with any name), and use the **Basic Kanban** template, containing *"To do"*, *"In Progress"*, and *"Done"*
2. Set up these automations:
- When pull requests are added, put the item in "In progress"
- When issues are closed, put the item in "Done"
- When pull requests are merged, put the item in "Done"
3. Regularly visit the **Issues** and **Pull requests** tabs to make sure all items are marked with your project board

**Comment by chang2000** [comment]
Board created and automations have been set.

**Comment by chang2000** [comment]
close
